# 评分卡案例

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression as LR

In [2]:
data = pd.read_csv("rankingcard.csv", index_col=0)

In [3]:
data.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [4]:
data.shape

(150000, 11)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150000 entries, 1 to 150000
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      150000 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 4   DebtRatio                             150000 non-null  float64
 5   MonthlyIncome                         120269 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 7   NumberOfTimes90DaysLate               150000 non-null  int64
 8   NumberRealEstateLoansOrLines          150000 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 10  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 13.7 MB

In [6]:
# 去重
data.drop_duplicates(inplace=True)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 149391 entries, 1 to 150000
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149391 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149391 non-null  float64
 2   age                                   149391 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149391 non-null  int64
 4   DebtRatio                             149391 non-null  float64
 5   MonthlyIncome                         120170 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149391 non-null  int64
 7   NumberOfTimes90DaysLate               149391 non-null  int64
 8   NumberRealEstateLoansOrLines          149391 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149391 non-null  int64
 10  NumberOfDependents                    145563 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 13.7 MB

In [8]:
# 重设索引
data1 = data.reset_index(drop=True)
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149391 entries, 0 to 149390
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149391 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149391 non-null  float64
 2   age                                   149391 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149391 non-null  int64
 4   DebtRatio                             149391 non-null  float64
 5   MonthlyIncome                         120170 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149391 non-null  int64
 7   NumberOfTimes90DaysLate               149391 non-null  int64
 8   NumberRealEstateLoansOrLines          149391 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149391 non-null  int64
 10  NumberOfDependents                    145563 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.5 MB

In [9]:
data.index = range(data.shape[0])

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149391 entries, 0 to 149390
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149391 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149391 non-null  float64
 2   age                                   149391 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149391 non-null  int64
 4   DebtRatio                             149391 non-null  float64
 5   MonthlyIncome                         120170 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149391 non-null  int64
 7   NumberOfTimes90DaysLate               149391 non-null  int64
 8   NumberRealEstateLoansOrLines          149391 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149391 non-null  int64
 10  NumberOfDependents                    145563 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.5 MB

缺失值填充

In [11]:
# 空值
data.isnull().mean()

SeriousDlqin2yrs                        0.000000
RevolvingUtilizationOfUnsecuredLines    0.000000
age                                     0.000000
NumberOfTime30-59DaysPastDueNotWorse    0.000000
DebtRatio                               0.000000
MonthlyIncome                           0.195601
NumberOfOpenCreditLinesAndLoans         0.000000
NumberOfTimes90DaysLate                 0.000000
NumberRealEstateLoansOrLines            0.000000
NumberOfTime60-89DaysPastDueNotWorse    0.000000
NumberOfDependents                      0.025624
dtype: float64

In [12]:
# 月收入比较重要，不能删除；家属数量的缺失比较少，不重要，可以删除缺失行。
# 均值填充家属数量
data["NumberOfDependents"].fillna(data["NumberOfDependents"].mean(), inplace=True)

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149391 entries, 0 to 149390
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149391 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149391 non-null  float64
 2   age                                   149391 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149391 non-null  int64
 4   DebtRatio                             149391 non-null  float64
 5   MonthlyIncome                         120170 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149391 non-null  int64
 7   NumberOfTimes90DaysLate               149391 non-null  int64
 8   NumberRealEstateLoansOrLines          149391 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149391 non-null  int64
 10  NumberOfDependents                    149391 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.5 MB

In [18]:
# 对于月收入的填充，猜测是低收入人群，但实际中缺失的原因比较多样，需要和业务人员沟通
# 这里采用随机森林填充。
def fill_missing_rf(X, y, to_fill):
    """使用随机森林填补一个特征的缺失值

    Args:
        X (_type_): 要填补的特征矩阵
        y (_type_): 没有缺失值的标签
        to_fill (_type_): 字符串，要填充的列名
    """
    df = X.copy()
    fill = df.loc[:, to_fill]
    df = pd.concat([df.loc[:, df.columns != to_fill], pd.DataFrame(y)], axis=1)
    
    Ytrain = fill[fill.notnull()]
    Ytest = fill[fill.isnull()]
    Xtrain = df.iloc[Ytrain.index, :]
    Xtest = df.iloc[Ytest.index, :]
    
    from sklearn.ensemble import RandomForestRegressor as rfr
    rfr = rfr(n_estimators=100, n_jobs=-1)
    rfr = rfr.fit(Xtrain, Ytrain)
    Ypredict = rfr.predict(Xtest)
    
    return Ypredict

In [15]:
X = data.iloc[:, 1:]
y = data.iloc[:, 0]
X.shape

(149391, 10)

In [19]:
Ypredict = fill_missing_rf(X, y, "MonthlyIncome")

In [20]:
data.loc[data.loc[:, "MonthlyIncome"].isnull(), "MonthlyIncome"] = Ypredict

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149391 entries, 0 to 149390
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149391 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149391 non-null  float64
 2   age                                   149391 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149391 non-null  int64
 4   DebtRatio                             149391 non-null  float64
 5   MonthlyIncome                         149391 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149391 non-null  int64
 7   NumberOfTimes90DaysLate               149391 non-null  int64
 8   NumberRealEstateLoansOrLines          149391 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149391 non-null  int64
 10  NumberOfDependents                    149391 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.5 MB

In [22]:
# 描述性统计，返回特定的分位数
data.describe([0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99])

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,149391.000000,149391.000000,149391.000000,149391.000000,149391.000000,1.493910e+05,149391.000000,149391.000000,149391.000000,149391.000000,149391.000000
mean,0.066999,6.071087,52.306237,0.393886,354.436740,5.428470e+03,8.480892,0.238120,1.022391,0.212503,0.759863
std,0.250021,250.263672,14.725962,3.852953,2041.843455,1.326070e+04,5.136515,3.826165,1.130196,3.810523,1.101749
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
1%,0.000000,0.000000,24.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
10%,0.000000,0.003199,33.000000,0.000000,0.034991,1.800000e-01,3.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.030132,41.000000,0.000000,0.177441,1.800000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.154235,52.000000,0.000000,0.368234,4.432000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,0.556494,63.000000,0.000000,0.875279,7.416000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
90%,0.000000,0.978007,72.000000,1.000000,1275.000000,1.080000e+04,15.000000,0.000000,2.000000,0.000000,2.000000
99%,1.000000,1.093922,87.000000,4.000000,4985.100000,2.325000e+04,24.000000,3.000000,4.000000,2.000000,4.000000
max,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [23]:
# 发现有年龄为0的列
(data["age"] == 0).sum()

1

In [24]:
data = data[data["age"] != 0]

In [25]:
data.shape

(149390, 11)

异常值处理

In [26]:
data[data.loc[:, "NumberOfTimes90DaysLate"] > 90]

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1732,1,1.0,27,98,0.0,2700.000000,0,98,0,98,0.000000
2285,0,1.0,22,98,0.0,1350.823532,0,98,0,98,0.000000
3883,0,1.0,38,98,12.0,2692.270000,0,98,0,98,0.000000
4416,0,1.0,21,98,0.0,0.000000,0,98,0,98,0.000000
4704,0,1.0,21,98,0.0,2000.000000,0,98,0,98,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
146667,1,1.0,25,98,0.0,2251.806857,0,98,0,98,0.759863
147180,1,1.0,68,98,255.0,8.120000,0,98,0,98,0.000000
148548,1,1.0,24,98,54.0,919.280000,0,98,0,98,0.000000
148634,0,1.0,26,98,0.0,2000.000000,0,98,0,98,0.000000
148833,1,1.0,34,98,9.0,2797.070000,0,98,0,98,0.000000

In [27]:
data.loc[:, "NumberOfTimes90DaysLate"].value_counts()

NumberOfTimes90DaysLate
0     141107
1       5232
2       1555
3        667
4        291
98       220
5        131
6         80
7         38
8         21
9         19
10         8
96         5
11         5
13         4
15         2
14         2
12         2
17         1
Name: count, dtype: int64

In [28]:
# 去除异常值
data = data[data.loc[:, "NumberOfTimes90DaysLate"] < 90]

In [29]:
data.shape

(149165, 11)

In [30]:
data.describe()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,149165.000000,149165.000000,149165.000000,149165.000000,149165.000000,1.491650e+05,149165.000000,149165.000000,149165.000000,149165.000000,149165.000000
mean,0.066188,6.078770,52.331076,0.246720,354.963542,5.432548e+03,8.493688,0.090725,1.023927,0.065069,0.760325
std,0.248612,250.453111,14.714114,0.698935,2043.344496,1.326989e+04,5.129841,0.486354,1.130350,0.330675,1.102024
min,0.000000,0.000000,21.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.030033,41.000000,0.000000,0.178211,1.800000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.153615,52.000000,0.000000,0.368619,4.443000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,0.553698,63.000000,0.000000,0.876994,7.420000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,1.000000,50708.000000,109.000000,13.000000,329664.000000,3.008750e+06,58.000000,17.000000,54.000000,11.000000,20.000000

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 149165 entries, 0 to 149390
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149165 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149165 non-null  float64
 2   age                                   149165 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149165 non-null  int64
 4   DebtRatio                             149165 non-null  float64
 5   MonthlyIncome                         149165 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149165 non-null  int64
 7   NumberOfTimes90DaysLate               149165 non-null  int64
 8   NumberRealEstateLoansOrLines          149165 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149165 non-null  int64
 10  NumberOfDependents                    149165 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 13.7 MB

恢复索引

In [32]:
data.reset_index(drop=True, inplace=True)

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149165 entries, 0 to 149164
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      149165 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  149165 non-null  float64
 2   age                                   149165 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  149165 non-null  int64
 4   DebtRatio                             149165 non-null  float64
 5   MonthlyIncome                         149165 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       149165 non-null  int64
 7   NumberOfTimes90DaysLate               149165 non-null  int64
 8   NumberRealEstateLoansOrLines          149165 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  149165 non-null  int64
 10  NumberOfDependents                    149165 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.5 MB

---

偏态分布处理

In [34]:
X = data.iloc[:, 1:]
y = data.iloc[:, 0]

In [35]:
y.value_counts()

SeriousDlqin2yrs
0    139292
1      9873
Name: count, dtype: int64

In [36]:
sample0 = y.value_counts()[0] / y.shape[0]
sample1 = 1 - sample0
print(sample0, sample1)

0.9338115509670499 0.06618844903295007

In [38]:
# 上采样库
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X, y = sm.fit_resample(X, y)

n_sample_ = X.shape[0]

In [39]:
X.shape

(278584, 10)

In [40]:
sample0_ = y.value_counts()[0] / X.shape[0]
sample1_ = 1 - sample0_
print(sample0_, sample1_)

0.5 0.5

In [41]:
y.value_counts()

SeriousDlqin2yrs
1    139292
0    139292
Name: count, dtype: int64

---

训练集和测试集划分

In [42]:
from sklearn.model_selection import train_test_split
X = pd.DataFrame(X)
y = pd.DataFrame(y)

X_train, X_vali, Y_train, Y_vali = train_test_split(X, y, test_size=0.3, random_state=42)

In [43]:
# 组合训练集的特征矩阵和标签
model_data = pd.concat([Y_train, X_train], axis=1)

In [45]:
model_data.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
228626,1,0.999845,38,0,0.202286,3919.876814,7,0,0,0,0.969204
77755,0,0.067156,59,0,0.377116,9744.000000,25,0,2,0,0.000000
141145,0,0.030254,51,0,0.615891,3800.000000,16,0,2,0,0.000000
171258,1,0.469502,64,0,4487.780696,0.036803,12,0,1,0,0.000000
126241,0,0.025159,40,0,0.178416,13333.000000,6,0,1,0,0.000000

In [46]:
# columns正常不用调整；index需要重设
model_data.reset_index(drop=True, inplace=True)

In [47]:
vali_data = pd.concat([X_vali, Y_vali], axis=1)
vali_data.reset_index(drop=True, inplace=True)

In [48]:
model_data.to_csv("model_data.csv")
vali_data.to_csv("vali_data.csv")

In [2]:
model_data = pd.read_csv("model_data.csv")
vali_data = pd.read_csv("vali_data.csv")

---

分箱

In [3]:
# 以age为例
model_data["qcut"], updown = pd.qcut(model_data["age"], retbins=True, q=20)
# updown: 每个箱子的上下界
# retbins为True会额外返回以样本索引为索引，被分到的箱子为元素的Series。新列`qcut`的内容为该Series

In [4]:
model_data.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,qcut
0,0,1,0.999845,38,0,0.202286,3919.876814,7,0,0,0,0.969204,"(36.0, 39.0]"
1,1,0,0.067156,59,0,0.377116,9744.000000,25,0,2,0,0.000000,"(58.0, 61.0]"
2,2,0,0.030254,51,0,0.615891,3800.000000,16,0,2,0,0.000000,"(50.0, 52.0]"
3,3,1,0.469502,64,0,4487.780696,0.036803,12,0,1,0,0.000000,"(61.0, 64.0]"
4,4,0,0.025159,40,0,0.178416,13333.000000,6,0,1,0,0.000000,"(39.0, 41.0]"

In [5]:
model_data["qcut"].value_counts()

qcut
(36.0, 39.0]      12727
(20.999, 28.0]    11700
(58.0, 61.0]      11592
(45.0, 47.0]      11119
(48.0, 50.0]      11022
(31.0, 34.0]      10809
(50.0, 52.0]      10543
(43.0, 45.0]      10297
(61.0, 64.0]      10198
(52.0, 54.0]       9784
(39.0, 41.0]       9735
(41.0, 43.0]       9669
(28.0, 31.0]       9514
(74.0, 109.0]      9125
(64.0, 68.0]       8955
(54.0, 56.0]       8728
(68.0, 74.0]       8592
(56.0, 58.0]       7946
(34.0, 36.0]       7468
(47.0, 48.0]       5485
Name: count, dtype: int64

In [6]:
updown

array([ 21.,  28.,  31.,  34.,  36.,  39.,  41.,  43.,  45.,  47.,  48.,
        50.,  52.,  54.,  56.,  58.,  61.,  64.,  68.,  74., 109.])

In [7]:
# 提取每个箱中0的个数
count_y0 = model_data[model_data["SeriousDlqin2yrs"] == 0].groupby(by="qcut").count()["SeriousDlqin2yrs"]
count_y0

qcut
(20.999, 28.0]    4226
(28.0, 31.0]      3558
(31.0, 34.0]      4056
(34.0, 36.0]      2824
(36.0, 39.0]      5126
(39.0, 41.0]      3935
(41.0, 43.0]      4044
(43.0, 45.0]      4407
(45.0, 47.0]      4757
(47.0, 48.0]      2487
(48.0, 50.0]      4933
(50.0, 52.0]      4732
(52.0, 54.0]      4697
(54.0, 56.0]      4660
(56.0, 58.0]      4480
(58.0, 61.0]      6777
(61.0, 64.0]      7005
(64.0, 68.0]      6644
(68.0, 74.0]      6766
(74.0, 109.0]     7754
Name: SeriousDlqin2yrs, dtype: int64

In [8]:
count_y1 = model_data[model_data["SeriousDlqin2yrs"] == 1].groupby(by="qcut").count()["SeriousDlqin2yrs"]
count_y1

qcut
(20.999, 28.0]    7474
(28.0, 31.0]      5956
(31.0, 34.0]      6753
(34.0, 36.0]      4644
(36.0, 39.0]      7601
(39.0, 41.0]      5800
(41.0, 43.0]      5625
(43.0, 45.0]      5890
(45.0, 47.0]      6362
(47.0, 48.0]      2998
(48.0, 50.0]      6089
(50.0, 52.0]      5811
(52.0, 54.0]      5087
(54.0, 56.0]      4068
(56.0, 58.0]      3466
(58.0, 61.0]      4815
(61.0, 64.0]      3193
(64.0, 68.0]      2311
(68.0, 74.0]      1826
(74.0, 109.0]     1371
Name: SeriousDlqin2yrs, dtype: int64

In [9]:
# 每个箱的上界和下界以及箱内的0和1总个数
num_bins = [*zip(updown, updown[1:], count_y0, count_y1)]
num_bins

[(21.0, 28.0, 4226, 7474),
 (28.0, 31.0, 3558, 5956),
 (31.0, 34.0, 4056, 6753),
 (34.0, 36.0, 2824, 4644),
 (36.0, 39.0, 5126, 7601),
 (39.0, 41.0, 3935, 5800),
 (41.0, 43.0, 4044, 5625),
 (43.0, 45.0, 4407, 5890),
 (45.0, 47.0, 4757, 6362),
 (47.0, 48.0, 2487, 2998),
 (48.0, 50.0, 4933, 6089),
 (50.0, 52.0, 4732, 5811),
 (52.0, 54.0, 4697, 5087),
 (54.0, 56.0, 4660, 4068),
 (56.0, 58.0, 4480, 3466),
 (58.0, 61.0, 6777, 4815),
 (61.0, 64.0, 7005, 3193),
 (64.0, 68.0, 6644, 2311),
 (68.0, 74.0, 6766, 1826),
 (74.0, 109.0, 7754, 1371)]

In [10]:
# 确定每个箱中有0和1